/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SearchResult = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'snippet' : IDL.Text,
});
export const AgenticResult = IDL.Record({
  'contextMode' : IDL.Text,
  'results' : IDL.Vec(SearchResult),
  'timestamp' : IDL.Int,
  'searchQuery' : IDL.Text,
  'actionableSummary' : IDL.Text,
});
export const DataRow = IDL.Record({
  'id' : IDL.Text,
  'component' : IDL.Text,
  'createdAt' : IDL.Int,
  'specification' : IDL.Text,
  'toolsRequired' : IDL.Text,
});
export const KnowledgeDoc = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const ScanResult = IDL.Record({
  'id' : IDL.Text,
  'contextMode' : IDL.Text,
  'analysisText' : IDL.Text,
  'timestamp' : IDL.Int,
  'thumbnailSummary' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'agenticScan' : IDL.Func([IDL.Text, IDL.Text], [AgenticResult], []),
  'deleteDataRow' : IDL.Func([IDL.Text], [], []),
  'deleteKnowledgeDoc' : IDL.Func([IDL.Text], [], []),
  'deleteScanResult' : IDL.Func([IDL.Text], [], []),
  'getDataRows' : IDL.Func([], [IDL.Vec(DataRow)], ['query']),
  'getKnowledgeDocs' : IDL.Func([], [IDL.Vec(KnowledgeDoc)], ['query']),
  'getScanResults' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
  'hasGeminiKey' : IDL.Func([], [IDL.Bool], ['query']),
  'saveDataRow' : IDL.Func([DataRow], [], []),
  'saveKnowledgeDoc' : IDL.Func([KnowledgeDoc], [], []),
  'saveScanResult' : IDL.Func([ScanResult], [], []),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'visionScan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'webSearch' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], []),
  'whoami' : IDL.Func([], [IDL.Principal], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SearchResult = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'snippet' : IDL.Text,
  });
  const AgenticResult = IDL.Record({
    'contextMode' : IDL.Text,
    'results' : IDL.Vec(SearchResult),
    'timestamp' : IDL.Int,
    'searchQuery' : IDL.Text,
    'actionableSummary' : IDL.Text,
  });
  const DataRow = IDL.Record({
    'id' : IDL.Text,
    'component' : IDL.Text,
    'createdAt' : IDL.Int,
    'specification' : IDL.Text,
    'toolsRequired' : IDL.Text,
  });
  const KnowledgeDoc = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const ScanResult = IDL.Record({
    'id' : IDL.Text,
    'contextMode' : IDL.Text,
    'analysisText' : IDL.Text,
    'timestamp' : IDL.Int,
    'thumbnailSummary' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'agenticScan' : IDL.Func([IDL.Text, IDL.Text], [AgenticResult], []),
    'deleteDataRow' : IDL.Func([IDL.Text], [], []),
    'deleteKnowledgeDoc' : IDL.Func([IDL.Text], [], []),
    'deleteScanResult' : IDL.Func([IDL.Text], [], []),
    'getDataRows' : IDL.Func([], [IDL.Vec(DataRow)], ['query']),
    'getKnowledgeDocs' : IDL.Func([], [IDL.Vec(KnowledgeDoc)], ['query']),
    'getScanResults' : IDL.Func([], [IDL.Vec(ScanResult)], ['query']),
    'hasGeminiKey' : IDL.Func([], [IDL.Bool], ['query']),
    'saveDataRow' : IDL.Func([DataRow], [], []),
    'saveKnowledgeDoc' : IDL.Func([KnowledgeDoc], [], []),
    'saveScanResult' : IDL.Func([ScanResult], [], []),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'visionScan' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'webSearch' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], []),
    'whoami' : IDL.Func([], [IDL.Principal], []),
  });
};

export const init = ({ IDL }) => { return []; };
