/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgenticResult {
  'contextMode' : string,
  'results' : Array<SearchResult>,
  'timestamp' : bigint,
  'searchQuery' : string,
  'actionableSummary' : string,
}
export interface DataRow {
  'id' : string,
  'component' : string,
  'createdAt' : bigint,
  'specification' : string,
  'toolsRequired' : string,
}
export interface KnowledgeDoc {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface ScanResult {
  'id' : string,
  'contextMode' : string,
  'analysisText' : string,
  'timestamp' : bigint,
  'thumbnailSummary' : string,
}
export interface SearchResult {
  'url' : string,
  'title' : string,
  'snippet' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'agenticScan' : ActorMethod<[string, string], AgenticResult>,
  'deleteDataRow' : ActorMethod<[string], undefined>,
  'deleteKnowledgeDoc' : ActorMethod<[string], undefined>,
  'deleteScanResult' : ActorMethod<[string], undefined>,
  'getDataRows' : ActorMethod<[], Array<DataRow>>,
  'getKnowledgeDocs' : ActorMethod<[], Array<KnowledgeDoc>>,
  'getScanResults' : ActorMethod<[], Array<ScanResult>>,
  'hasGeminiKey' : ActorMethod<[], boolean>,
  'saveDataRow' : ActorMethod<[DataRow], undefined>,
  'saveKnowledgeDoc' : ActorMethod<[KnowledgeDoc], undefined>,
  'saveScanResult' : ActorMethod<[ScanResult], undefined>,
  'setGeminiApiKey' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'visionScan' : ActorMethod<[string, string, string], string>,
  'webSearch' : ActorMethod<[string], Array<SearchResult>>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
