/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DataRow {
  'id' : string,
  'component' : string,
  'createdAt' : bigint,
  'specification' : string,
  'toolsRequired' : string,
}
export interface KnowledgeDoc {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface _SERVICE {
  'deleteDataRow' : ActorMethod<[string], undefined>,
  'deleteKnowledgeDoc' : ActorMethod<[string], undefined>,
  'getDataRows' : ActorMethod<[], Array<DataRow>>,
  'getKnowledgeDocs' : ActorMethod<[], Array<KnowledgeDoc>>,
  'saveDataRow' : ActorMethod<[DataRow], undefined>,
  'saveKnowledgeDoc' : ActorMethod<[KnowledgeDoc], undefined>,
  'whoami' : ActorMethod<[], Principal>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];