/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DataRow = IDL.Record({
  'id' : IDL.Text,
  'component' : IDL.Text,
  'createdAt' : IDL.Int,
  'specification' : IDL.Text,
  'toolsRequired' : IDL.Text,
});
export const KnowledgeDoc = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteDataRow' : IDL.Func([IDL.Text], [], []),
  'deleteKnowledgeDoc' : IDL.Func([IDL.Text], [], []),
  'getDataRows' : IDL.Func([], [IDL.Vec(DataRow)], ['query']),
  'getKnowledgeDocs' : IDL.Func([], [IDL.Vec(KnowledgeDoc)], ['query']),
  'saveDataRow' : IDL.Func([DataRow], [], []),
  'saveKnowledgeDoc' : IDL.Func([KnowledgeDoc], [], []),
  'whoami' : IDL.Func([], [IDL.Principal], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DataRow = IDL.Record({
    'id' : IDL.Text,
    'component' : IDL.Text,
    'createdAt' : IDL.Int,
    'specification' : IDL.Text,
    'toolsRequired' : IDL.Text,
  });
  const KnowledgeDoc = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteDataRow' : IDL.Func([IDL.Text], [], []),
    'deleteKnowledgeDoc' : IDL.Func([IDL.Text], [], []),
    'getDataRows' : IDL.Func([], [IDL.Vec(DataRow)], ['query']),
    'getKnowledgeDocs' : IDL.Func([], [IDL.Vec(KnowledgeDoc)], ['query']),
    'saveDataRow' : IDL.Func([DataRow], [], []),
    'saveKnowledgeDoc' : IDL.Func([KnowledgeDoc], [], []),
    'whoami' : IDL.Func([], [IDL.Principal], []),
  });
};

export const init = ({ IDL }) => { return []; };