/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchResult {
    url: string;
    title: string;
    snippet: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ScanResult {
    id: string;
    contextMode: string;
    analysisText: string;
    timestamp: bigint;
    thumbnailSummary: string;
}
export interface KnowledgeDoc {
    id: string;
    title: string;
    content: string;
    createdAt: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DataRow {
    id: string;
    component: string;
    createdAt: bigint;
    specification: string;
    toolsRequired: string;
}
export interface AgenticResult {
    contextMode: string;
    results: Array<SearchResult>;
    timestamp: bigint;
    searchQuery: string;
    actionableSummary: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    agenticScan(imageDescription: string, contextMode: string): Promise<AgenticResult>;
    deleteDataRow(id: string): Promise<void>;
    deleteKnowledgeDoc(id: string): Promise<void>;
    deleteScanResult(id: string): Promise<void>;
    getDataRows(): Promise<Array<DataRow>>;
    getKnowledgeDocs(): Promise<Array<KnowledgeDoc>>;
    getScanResults(): Promise<Array<ScanResult>>;
    saveDataRow(row: DataRow): Promise<void>;
    saveKnowledgeDoc(doc: KnowledgeDoc): Promise<void>;
    saveScanResult(result: ScanResult): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    visionScan(imageBase64: string, _prompt: string, _contextMode: string): Promise<string>;
    webSearch(_query: string): Promise<Array<SearchResult>>;
    whoami(): Promise<Principal>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async agenticScan(arg0: string, arg1: string): Promise<AgenticResult> {
        if (this.processError) {
            try {
                const result = await this.actor.agenticScan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.agenticScan(arg0, arg1);
            return result;
        }
    }
    async deleteDataRow(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDataRow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDataRow(arg0);
            return result;
        }
    }
    async deleteKnowledgeDoc(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKnowledgeDoc(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKnowledgeDoc(arg0);
            return result;
        }
    }
    async deleteScanResult(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScanResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScanResult(arg0);
            return result;
        }
    }
    async getDataRows(): Promise<Array<DataRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDataRows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDataRows();
            return result;
        }
    }
    async getKnowledgeDocs(): Promise<Array<KnowledgeDoc>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnowledgeDocs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnowledgeDocs();
            return result;
        }
    }
    async getScanResults(): Promise<Array<ScanResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScanResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScanResults();
            return result;
        }
    }
    async saveDataRow(arg0: DataRow): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDataRow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDataRow(arg0);
            return result;
        }
    }
    async saveKnowledgeDoc(arg0: KnowledgeDoc): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveKnowledgeDoc(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveKnowledgeDoc(arg0);
            return result;
        }
    }
    async saveScanResult(arg0: ScanResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveScanResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveScanResult(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async visionScan(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.visionScan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.visionScan(arg0, arg1, arg2);
            return result;
        }
    }
    async webSearch(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.webSearch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.webSearch(arg0);
            return result;
        }
    }
    async whoami(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.whoami();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoami();
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
